frontend_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp/', include('webapp.urls', namespace='webapp')),
]

webapp/urls.py
from django.urls import path

from . import views

app_name = 'webapp'
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_request, name="login view"),
    path("upload-dataset/", views.upload_dataset, name="upload dataset view"),
    path("logout/", views.logout_view, name="logout"),
    # path("profile/", views.profile_view, name="profile"),
    # path("login-retry-view/", views.login_retry_view, name="login retry view"),
    # path("login-view/login/", views.login_user, name="login"),
    # path("login-retry-view/login/", views.login_user, name="retry login"),
    # path("register-view/", views.register_view, name="register view"),
    # path("register-retry-view/", views.register_retry_view, name="register retry view"),
    # path("register-view/register/", views.register, name="register"),
    # path("register-retry-view/register/", views.register, name="register retry "),
    # path("upload-model/", views.upload_model, name="upload model form"),
    # path("public-dataset-list-view/", views.public_dataset_list_view, name="public dataset list view"),
    # path("public-model-list-view/", views.public_model_list_view, name="public model list view"),
    # path("public-dataset-data-view:<int:pk>/", views.public_dataset_list_view, name="public-dataset-data-view"),
    # path("private-dataset-list-view/", views.private_dataset_list_view, name="private-dataset-list-view"),
    # path("private-model-list-view/", views.private_model_list_view, name="private-model-list-view"),
    # path("user_dataset_list_path_view/", views.user_dataset_list_path_view, name="user_dataset_list_path_view"),
    # path("process-model-options/", views.process_model_options_view, name="process model options"),
    # path("human-reinforced-feedback/", views.human_reinforced_feedback_view, name="human reinforced feedback view"),
    # path("final-task-analytics/", views.final_task_analytics_view, name="final task analytics"),
    # path("previous-tasks/", views.previous_tasks_view, name="previous tasks"),
    # path("personal-model-repo/", views.personal_model_repo_view, name="personal model repo"),
    # path("personal-dataset-repo/", views.personal_dataset_repo_view, name="personal dataset repo"),
    # path("personal-dataset-analysis/", views.personal_dataset_analysis_view, name="personal dataset analysis"),
]

webapp/models.py
from django.db import models

# Create your models here.

webapp/views.py
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from django.utils import timezone
from django import forms
from io import BytesIO
import zipfile
import requests
import json
import os
import ast

UTF8 = 'utf-8'
API_URL = "http://127.0.0.1:8000/polls/"

ROOT_TEMP = 'asset/temp/test'

class UploadDatasetForm(forms.Form):
    name = forms.CharField(max_length=320)
    dataset = forms.FileField(required=False)
    zipfile = forms.FileField(required=False)  
    directories = forms.CharField(required=False)
    
    CHOICES = [
        ('1', 'private'),
        ('2', 'public'),
    ]

    is_public = forms.ChoiceField(
        label="Publicity",
        widget=forms.RadioSelect,
        choices=CHOICES, 
        required=False,
    )

def bstr(byte_string, encoding=UTF8):
    return byte_string.decode(encoding)    

def get_request(request):
    template_name = 'webapp/empty.html'
    url = API_URL

    response = requests.get(url)

    context = { 'htmlstring': bstr(response.content)}
    return render(request, template_name, context)

def create_in_memory_zip_with_files_and_directories(files: list, directories: dict) -> bytes:
    memory_file = BytesIO()
    with zipfile.ZipFile(memory_file, 'w') as zipf:
        for file in files:
            relative_file_path = directories.get(file.name)

            if not relative_file_path:
                continue
            
            zipf.writestr(relative_file_path, file.read())

    memory_file.seek(0)
    return memory_file.read()

def login_request(request):
    template_name = "registration/login_view.html"
    url = f"{API_URL}login-api/"
    context = {}

    if request.method != "POST":
        return render(request, template_name, context)

    username = request.POST["username"]
    password = request.POST["password"]

    request.session._get_or_create_session_key()
    data = {
        "session_key": request.session.session_key, 
        "username": username, 
        "password": password, 
    }
    
    response = requests.post(url, json=data)
    print(' --- ', request, request.user, request.user.is_authenticated, data['session_key'])
    print(' --- ', response)
    
    response_data = json.loads(response.text)
    print(' --- ', response)
    
    if response_data['is_authenticated'] == True:
        request.session['token'] = response_data['token']
        return redirect("/webapp/upload-dataset/")    

    return render(request, template_name, context)

def unzip_and_save(zipfile_dir, timestamp):

    return

def save_zip_file(zipfile, timestamp: str, root_dir: str = ROOT_TEMP):
    save_filename = f"{timestamp}-{zipfile.name}"
    zipfile_dir = os.path.join(root_dir, save_filename)

    FileSystemStorage(location=root_dir).save(save_filename, zipfile)     
    return zipfile_dir

def save_zip_bytes_file(bytes, filename='a_zip_file.zip', root_dir=ROOT_TEMP):
    with open(os.path.join(root_dir, filename), "wb") as binary_file:
        binary_file.write(bytes)
    return

def now_Ymd_HMS(format='%Y%m%d_%H%M%S') -> str:
    return timezone.now().strftime(format)

def upload_dataset(request, template_name = "webapp/upload_dataset.html", context = {}):
    if request.method != "POST":
        form = UploadDatasetForm()
        return render(request, template_name, {"form": form} | context)
    
    form = UploadDatasetForm(request.POST, request.FILES)
    
    ispublic = request.POST.get("is_public")
    name = request.POST.get("name")
    
    directories_str = request.POST.get("directories")

    data = {
        'name': name,
        'ispublic': ispublic,
    }
    files = {}
    headers = {
        "Authorization": "",
    }
    
    if directories_str:
        directories_dict = ast.literal_eval(directories_str)

    zipfile_list = request.FILES.getlist('zipfile')

    if len(zipfile_list) != 0:
        zipfile = zipfile_list[0] # <class 'django.core.files.uploadedfile.TemporaryUploadedFile'>

        files['zipfile'] = zipfile

        timestamp = now_Ymd_HMS()
        zipfile_dir = save_zip_file(zipfile, timestamp)
        
        unzip_and_save(zipfile_dir, timestamp)

    dataset_files = request.FILES.getlist('file')

    if form.is_valid() and len(dataset_files) != 0 and len(directories_dict) != 0:
        zip_bytes_file = create_in_memory_zip_with_files_and_directories(dataset_files, directories_dict)
        timestamp = now_Ymd_HMS()
        files['zip_bytes_file'] = zip_bytes_file
        save_zip_bytes_file(zip_bytes_file)
    
    url = f"{API_URL}upload-dataset-api/"
    response = requests.post(url, json=data, files=files, headers=headers)
    
    response_data = json.loads(response.text)

    print(' - ', response_data)

    return render(request, template_name, {"form": form} | context)

def index(request):
    template_name = "webapp/index.html"
    base_html = "get_base_html(request.user.is_authenticated)"
    base_html = "base_guest.html"
    
    dataset_list = 'Dataset.objects.filter(is_public=True).order_by("-created")'
    paginator = 'Paginator(dataset_list, 2)'
    page_number = 'request.GET.get("dataset_page")'
    dataset_page_obj = 'paginator.get_page(page_number)'

    model_list = 'Model.objects.filter(is_public=True).order_by("-created")'
    model_paginator = 'Paginator(model_list, 2)'
    model_page_number = 'request.GET.get("model_page")'
    model_page_obj = 'model_paginator.get_page(model_page_number)'
    
    context = { 
        'base_html': base_html, 
        'dataset_page_obj': dataset_page_obj,
        'model_page_obj': model_page_obj,
    }

    return render(request, template_name, context)

def login(request, context={"please_login_message": "Please login to see this page."}):
    template_name = "registration/login_view.html"
    
    return render(request, template_name, context)

def logout_view(request):
    request.session['token'] = ''
    return redirect("/webapp/")

webapp/templates/base_guest.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block title %}Model Trainer{% endblock %}</title>
</head>

<body>    
    {% block topbar %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary d-block d-sm-none">
        <div class="container-fluid">
            <div class="d-flex me-3 gap-2">
                <h4>
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                        <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                        <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                    </svg>
                    logo
                </h4>
            </div>
            <form class="d-flex" role="search" action="search/">
                <input class="form-control me-2" type="search" placeholder="Search models, datasets, users..." aria-label="Search">
                <button class="btn btn-outline-secondary" type="submit">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                      </svg>
                </button>
            </form>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="/webapp/login/">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-door-open" viewBox="0 0 16 16">
                                <path d="M8.5 10c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1"/>
                                <path d="M10.828.122A.5.5 0 0 1 11 .5V1h.5A1.5 1.5 0 0 1 13 2.5V15h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117M11.5 2H11v13h1V2.5a.5.5 0 0 0-.5-.5M4 1.934V15h6V1.077z"/>
                            </svg>
                            Log In
                        </a>
                        <a class="nav-link active" aria-current="page" href="/webapp/login/">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z"/>
                                <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                            </svg>
                            Join
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>  
    {% endblock %}

    <div class="container-fluid " id="sidebar">
        <div class="row flex-nowrap">
            {% block sidebar %}
            <div class="col col-xl-1 col-md-2 col-sm-2 col-2 px-sm-1 px-0 d-none d-sm-inline bg-body-tertiary border border-light-subtle position-sticky top-0 start-0">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <ul class="nav nav-pills gap-2 mt-4 flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="">                            
                            <a href="/webapp/" class="px-0 text-black align-middle link-dark link-underline-dark link-underline-opacity-0 link-underline-opacity-25-hover">
                                <h4>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                        <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                                        <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                                    </svg>
                                    logo
                                </h4>
                            </a>
                        </li>
                        <li class="">
                            <a href="/webapp/login/" class=" px-0 text-black align-middle link-dark link-underline-dark link-underline-opacity-25 link-underline-opacity-50-hover">
                                <span class="ms-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-door-open" viewBox="0 0 16 16">
                                        <path d="M8.5 10c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1"/>
                                        <path d="M10.828.122A.5.5 0 0 1 11 .5V1h.5A1.5 1.5 0 0 1 13 2.5V15h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117M11.5 2H11v13h1V2.5a.5.5 0 0 0-.5-.5M4 1.934V15h6V1.077z"/>
                                    </svg>
                                    Log In
                                </span>
                            </a>
                        </li>
                        <li class="">
                            <a href="/webapp/register/" class="px-0 text-black align-middle link-underline-dark link-underline-opacity-25 link-underline-opacity-50-hover">                                
                            <span class="ms-1">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z"/>
                                    <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                                </svg>
                                Register
                            </span></a>
                        </li>
                        <li>
                            <form class="" role="search" action="search/">
                                <input class="form-control me-2" type="search" placeholder="Search models, datasets, users..." aria-label="Search">
                                <button class="btn btn-outline-secondary" type="submit">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                                      </svg>
                                </button>
                            </form>
                        </li>
                    </ul>
                    <hr>                    
                </div>
            </div>
            {% endblock %}

            <div id="content" class="col py-1">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

webapp/templates/webapp/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

webapp/templates/webapp/empty.html
{{ htmlstring |safe }}

webapp/templates/webapp/human_reinforced_feedback.html
{% extends "base_logged_in.html" %}

{% block content %}

<div class="container">
    <div class="col">
        <div class="box row p-1 mb-1 bg-body-tertiary rounded border border-light-subtle">
            <div>HITL Reinforced Feedback</div>
        </div>
        <div class="row gap-1">
            <div class="col p-1 mb-1 bg-body-tertiary rounded border border-light-subtle">
                <div>Recommendation 1</div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        Balance Data A
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        B
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        C
                    </label>
                </div>
            </div>
            <div class="col p-1 mb-1 bg-body-tertiary rounded border border-light-subtle">
                <div>Recommendation 2</div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        KD For the Model A
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        B
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        C
                    </label>
                </div>
            </div>
        </div>        
        <div class="row p-1 mb-1 bg-body-tertiary rounded border border-light-subtle">
            <div>Current Performance Analytics</div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    Result A
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    Result B
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    Result C
                </label>
            </div>
        </div>
        <div class="row gap-1">
            <button class="col btn btn-primary">
                Apply Recommendations
            </button>
            <button class="col btn btn-primary">
                Complete Process
            </button>
        </div>        
    </div>
</div>



{% endblock content %}

webapp/templates/webapp/personal_dataset_repo.html
{% extends "base_logged_in.html" %}

{% block content %}

<div class="container">
    <div class="col p-1 mb-1 bg-body-tertiary rounded border border-light-subtle">
        <h5>Dataset Management</h5>
    </div>
    <div class="row align-items-start gap-1">
        <div class="row gap-1">
            <div class="col p-1 bg-body-tertiary rounded border border-light-subtle">
                <div class="row gap-1 m-0">
                    <a class="btn btn-primary" href="/polls/personal-dataset-analysis/" role="button">Dataset 01</a>
                    <a class="btn btn-primary" href="/polls/personal-dataset-analysis/" role="button">Dataset 02</a>
                    <a class="btn btn-primary" href="/polls/personal-dataset-analysis/" role="button">Dataset 03</a>                    
                </div>
            </div>
            <div class="col p-1 bg-body-tertiary rounded border border-light-subtle">
                <div class="row gap-1 m-0">
                    <button class="btn btn-primary">Dataset Analysis</button>
                    <button class="btn btn-primary">Data Generation</button>
                    <button class="btn btn-primary">Cleaning</button>
                    <button class="btn btn-primary">Enrichment</button>
                    <button class="btn btn-primary">Data Curation</button>
                    <button class="btn btn-primary">Balancing</button>
                    <button class="btn btn-primary">XAI</button>
                </div>
            </div>
            <div class="col p-1 bg-body-tertiary rounded border border-light-subtle">
                Dataset Details
                <p></p>
                <p></p>
                <p></p>
            </div>
        </div>
        <div class="row gap-1">
            <button class="col btn btn-primary">
                Upload Dataset
            </button>
            <button class="col btn btn-danger">
                Delete Dataset
            </button>
            <button class="col btn btn-primary">
                Download / Export
            </button>
        </div>        
    </div>
</div>



{% endblock content %}

webapp/templates/webapp/personal_model_repo.html
{% extends "base_logged_in.html" %}

{% block content %}

<div class="container">
    <div class="col p-1 mb-1 bg-body-tertiary rounded border border-light-subtle">
        <h5>AI Model Management</h5>
    </div>
    <div class="row align-items-start gap-1">
        <div class="row gap-1">
            <div class="col p-1 bg-body-tertiary rounded border border-light-subtle">
                <div class="row gap-1 m-0">
                    <button class="btn btn-primary">Model 01</button>
                    <button class="btn btn-primary">Model 02</button>
                    <button class="btn btn-primary">Model 03</button>
                </div>
            </div>
            <div class="col p-1 bg-body-tertiary rounded border border-light-subtle">
                <div class="row gap-1 m-0">
                    <button class="btn btn-primary">Model Analysis</button>
                    <button class="btn btn-primary">Distillation</button>
                    <button class="btn btn-primary">Fine Tuning</button>
                    <button class="btn btn-primary">XAI</button>
                </div>
            </div>
            <div class="col p-1 bg-body-tertiary rounded border border-light-subtle">
                Task Details/Report
                <p></p>
                <p></p>
                <p></p>
            </div>
        </div>
        <div class="row gap-1">
            <button class="col btn btn-primary">
                Upload Model
            </button>
            <button class="col btn btn-danger">
                Delete Model
            </button>
            <button class="col btn btn-primary">
                Download / Export
            </button>
        </div>        
    </div>
</div>



{% endblock content %}

webapp/templates/webapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

webapp/templates/webapp/upload_dataset.html
{% extends "base_logged_in.html" %}

{% block content %}

<div class="container">

<h1>Upload a Folder</h1>

<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    
    <div class="form-floating mb-1">
        <input type="text" name="name" id="id_name" class="form-control" placeholder="">
        <label for="id_name">Name</label>
    </div>

    <!-- accept=".csv, .tsv, .jsonl, .json, .parquet, .arrow, .txt, .png, .jpg, .wav, .mp3, .tar, .bin, etc." -->
    <label for="id_folder" class="form-label">Folder and Multiple Files:</label>
    <input type="file" name="file" id="id_folder" class="form-control mb-1" webkitdirectory directory mozdirectory multiple>
    <input type="text" id="directories" name="directories" hidden/>

    <!-- accept=".zip, .gz, .zst, .bz2, .lz4, .xz" -->
    <label for="id_zipfile" class="form-label">Zip File:</label>
    <input type="file" accept=".zip,.rar,.7zip" name="zipfile" id="id_zipfile" class="form-control mb-1">    
    
    <div class="input-group mb-3">
        {{ form.filepaths.errors }}
        <label for="id_filepaths" class="input-group-text">File Paths</label>
        <select type="text" name="filepaths" id="id_filepaths" class="form-select">
            {% for field in form.filepaths %}
                {{ field }}
            {% endfor %}
        </select>
    </div>
    
    <fieldset>
        <div class="form-check">
            <label class="form-check-label" for="id_is_public_1">
                <input class="form-check-input" type="radio" name="is_public" value="2" id="id_is_public_1" required checked>
                public
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label" for="id_is_public_0">
                <input class="form-check-input" type="radio" name="is_public" value="1" id="id_is_public_0" required>
                private
            </label>
        </div>
    </fieldset>
    <br>
    
    <button type="submit" class="btn btn-primary">Upload</button>
</form>
<script>
    files = document.querySelector("#id_folder").files;
    document.querySelector("#id_folder").addEventListener("change", function() {
        files = document.querySelector("#id_folder").files;
        var directories = {}
        for (var file of files) {
            file.webkitRelativePath
            directories[file.name] = file.webkitRelativePath            
        }
        directories = JSON.stringify(directories);
        
        document.querySelector("#directories").value = directories
    });
</script>

</div>


{% endblock %}